// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJFHouPSpd2u8hPeyB0fKCIgoA9Ngn6D0',
    appId: '1:42326096754:web:9c863a9c57dd5a2c993beb',
    messagingSenderId: '42326096754',
    projectId: 'foodpanda-745ef',
    authDomain: 'foodpanda-745ef.firebaseapp.com',
    storageBucket: 'foodpanda-745ef.appspot.com',
    measurementId: 'G-VFZNGDJYJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTeQOHgz-URr1eJZ1qVpcH1nvwu2sM1SE',
    appId: '1:42326096754:android:9056d4ee109654ac993beb',
    messagingSenderId: '42326096754',
    projectId: 'foodpanda-745ef',
    storageBucket: 'foodpanda-745ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvPN-O-3anq0Had1pJyWMVubIEViDTp8',
    appId: '1:42326096754:ios:8b56f47b897e54d7993beb',
    messagingSenderId: '42326096754',
    projectId: 'foodpanda-745ef',
    storageBucket: 'foodpanda-745ef.appspot.com',
    iosClientId: '42326096754-tdltsekrten6hm9lcufjerral8890d5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvPN-O-3anq0Had1pJyWMVubIEViDTp8',
    appId: '1:42326096754:ios:969ae9d783c6a0d4993beb',
    messagingSenderId: '42326096754',
    projectId: 'foodpanda-745ef',
    storageBucket: 'foodpanda-745ef.appspot.com',
    iosClientId: '42326096754-9bkotti3t49fs1809g7lbcttl70ff7c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaClone.RunnerTests',
  );
}
